services:
  api:
   image: tunecraftdavid4/hng-task-2-api
   restart: always
   networks:
      - hng-task2

  frontend:
    image: tunecraftdavid4/hng-task-2-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always
    networks:
      - hng-task2


networks:
  hng-task2: